l=[5,4,3,2,"Kritan"]
#list is mutable and it can have data of any data type 
print(l[4])
print(l[-1])
print(l)
l.append(50)
print(l)
l.insert (1,100)
print (l)
print(15 in l)
print(100 in l)
print(l.count(2))
print(l.index("Kritan"))
print(l.index(3,0,7))# syntax l.index(number,inclusive start index , exclusive end index )
l.remove("Kritan")
print(l)
print(l.pop())
print(l.pop(0))
print(l)
del l[0:2]
print(l)
print(max(l))
print(min(l))
print(sum(l))
l.reverse()
print(l)
l.append(50)
l.append(1000)
l.sort()
print(l)
#note to use function like max, min, sum,sort they should be of same type 
